VERSION = 0.2

SIZE_WINDOW_WIDTH = 1400
SIZE_WINDOW_HEIGHT = 820
SIZE_WINDOW = str(SIZE_WINDOW_WIDTH) + "x" + str(SIZE_WINDOW_HEIGHT)

LOGO_PATH = 'logo.png'
SIZE_LOGO_WIDTH = 250
SIZE_LOGO_HEIGHT = 150
