
MIN_IN_SEC = 60
HALF_HOUR_IN_SEC = 1800
HOUR_IN_SEC = 3600
DAY_IN_SEC = 86400


SIZE_WINDOW_WIDTH = 1200
SIZE_WINDOW_HEIGHT = 800
SIZE_WINDOW = str(SIZE_WINDOW_WIDTH) + "x" + str(SIZE_WINDOW_HEIGHT)
SIZE_CONSOLE_WIDTH = 145
SIZE_FREQUENCYS_ENTRY_WIDTH = 10

DEFAULT_SENDING_DELAY = MIN_IN_SEC
DEFAULT_GRAPHS_REFRESHING_DELAY = MIN_IN_SEC
DEFAULT_COLLECT_SENSOR_DATA = 1
DEFAULT_LIMIT_COLLECTING_DATA_TO_GRAPH = 31
DEFAULT_IP = "127.0.1.1"
DEFAULT_PORT = 5050

NUMBER_OF_SENSORS = 4

FORMAT_TIME = "%H:%M:%S"

HEADER = 500  # ilość bajtów które będą pobrane - 64
EXIT_CODE = 666
